### ISSUE TITLE
no default for `config.Pkg` when using `--config`

### ISSUE THREAD

**Issue by asphaltbuffet** [go-simpler/sloggen#32]
The example config documentation claims that the default for `pkg:` is `slogx`:

```yaml
# the name for the generated package.
# default: slogx
pkg: example
```

However, that only gets set to default when not using a config file, as the default is part of the pkg flag. There should be a check in the constructor for a new config object that adds something there (instead of in the flag or in addition to the flag value).

There are no tests for reading a config file for `pkg: ""`

As a result, when creating the package, the call to `os.Mkdir(cfg.Pkg, 0o755)` fails with an unhelpful message passed to user:

```sh
❯ go run go-simpler.org/sloggen@latest -config ./.sloggen.yml
mkdir : no such file or directory
exit status 1
```

**Comment by tmzane** [comment]
Thanks for the report, fixed in #33.
